version: '3.5'

services:
 postgres-server:
  image: postgres:latest
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
  env_file:
   - .env_db_pgsql
  user: root
  stop_grace_period: 1m
  container_name: postgres-server
  networks:
   zbx_net:
    aliases:
     - postgres-server
     - pgsql-server
     - pgsql-database

 zabbix-server:
  build: ./server-pgsql/ubuntu
  image: zabbix-server-pgsql:ubuntu-3.4-local
  ports:
   - "10051:10051"
  container_name: zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
#   - ./zbx_env/etc/cron.d:/etc/cron.d:ro
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
# Deploy works only on docker swarm
# If use docker compose then add to cron or use systemd for auto start/restart
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
   restart_policy:
     condition: always
  env_file:
   - .env_db_pgsql
   - .env_srv
  user: root
  depends_on:
   - postgres-server
   - zabbix-java-gateway
  networks:
    zbx_net:
      ipv4_address: 172.16.239.20
      aliases:
        - zabbix-server
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "ubuntu"

 zabbix-java-gateway:
  build: ./java-gateway/ubuntu
  image: zabbix-java-gateway:ubuntu-3.4-local
  container_name: zabbix-java-gateway
  ports:
   - "10052:10052"
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 256M
  env_file:
   - .env_java
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-java-gateway
     - zabbix-java-gateway-ubuntu
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix Java Gateway"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "java-gateway"
   com.zabbix.os: "ubuntu"

 zabbix-web-nginx-pgsql:
  build: ./web-nginx-pgsql/ubuntu
  image: zabbix-web-nginx-pgsql:ubuntu-3.4-local
  container_name: zabbix-web-nginx-pgsql
  ports:
   - "80:80"
   - "443:443"
  links:
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
# Deploy works only on docker swarm
# If use docker compose then add to cron or use systemd for auto start/restart
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
   restart_policy:
     condition: always
  env_file:
   - .env_db_pgsql
   - .env_web
  user: root
  depends_on:
   - zabbix-server
  networks:
   zbx_net:
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s   # require docker-compose >= 3.5
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "ubuntu"




networks:
  zbx_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
#    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

