---
- hosts: hardware_servers
  vars_files:
    - ../vars/vault_credentials.yml
  vars:
    - ansible_ssh_user: ansible
    - ansible_ssh_pass: "{{ vault_ansible_ssh_password }}"
    - ansible_sudo_pass: "{{ vault_ansible_ssh_password }}"
  tasks:


# [[ "$(dpkg-query --showformat='${Version}' --show zabbix-agent)" < "1:3.4" && "$(dpkg-query --showformat='${Version}' --show zabbix-agent 2>&1|grep 'no packages found'|wc -l)" = 0 ]] && echo old;
    - block:
      - name: Download Zabbix Ubuntu 14 (Trusty) release deb file
        get_url: 
          url="https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+trusty_all.deb"
          dest="/tmp/zabbix-release_3.4-1.deb"
        when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 14

      - name: Download Zabbix Ubuntu 16 (Xenial) release deb file
        get_url: 
          url="https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+xenial_all.deb"
          dest="/tmp/zabbix-release_3.4-1.deb"
        when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 16

      - name: Download Zabbix Ubuntu 18 (bionic) release deb file
        get_url: 
          url="https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+bionic_all.deb"
          dest="/tmp/zabbix-release_3.4-1.deb"
        when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 18

      - name: Apt install Zabbix release in Ubuntu/Debian
        apt: deb="/tmp/zabbix-release_3.4-1.deb"
        when: ansible_os_family == "Debian"

      - name: Yum install Zabbix release in RHEL or CentOS
        yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-3.4-2.el{{ ansible_distribution_major_version }}.noarch.rpm
        when: ansible_os_family == "RedHat"
      
      - name: Apt install Zabbix agent
        apt:
          name: zabbix-agent
          update_cache: yes
          dpkg_options: 'force-confnew,force-confdef'
          state: latest
        when: ansible_os_family == "Debian"

      - name: Yum install Zabbix agent
        yum: 
          name: zabbix-agent
          update_cache: yes
        when: ansible_os_family == "RedHat"

      - name: Unmask and restart zabbix agent
        systemd:
          name: zabbix-agent
          daemon_reload: yes
          masked: no
          enabled: yes
          state: restarted

      become: yes
